### ISSUE TITLE
Help? Need Next Level to Show When Answer Is Right!

### ISSUE THREAD

**Issue by VEESCREAMS** [VEESCREAMS/epicgamers#7]
For the file, "patterns_2019_05_21_18_08_21.zip". I also want the 'victory scene' (cs.js) to show when you finish level 8, before moving onto math. You can see the answers in "patternsinfo", which is a nother file in the respritory

**Comment by ULT01** [comment]
we decided not to include a victory scene for the pattern levels, but we did successfully have a victory scene for the addition levels
